name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [v22.12.0]

    env:
      NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm build --if-present
      - name: Change Directory
        run: cd /home/ivjose/actions-runner/_work/ivjose-latest/ivjose-latest
      - run: pm2 restart 0
